name: GitHub Actions Demo

on: 
  push:
    branches: [main]
    paths-ignore: ['.github/**']
  pull_request:
    branches: [main]
  schedule: 
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy environment'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output the name of the event that triggered the workflow
        run: echo "event name is:" ${{ github.event_name }}
      - name: Output the name of the branch that the repository is currently referencing
        run: echo " branch name is:" ${{ github.ref }}
      - uses: actions/checkout@v4

      - name: List file of directory
        run: tree

  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: [build]
    environment: 
      name: Test
    steps:
      - name: Workflow Test
        run: echo "Testing..."
  load-test:
    name: Load-Test
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: [build]
    environment: 
      name: Load-Test
    steps:
      - name: Workflow load-Test
        run: |
          echo "Testing..."
          sleep 15
  production:
    name: Production
    runs-on: ubuntu-latest
    needs: [test, load-test]
    environment: 
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo "Step 1 deploying"
          sleep 10
      - run: |
          echo "Step 2 deploying"
          sleep 10
      - run: |
          echo "Step 3 deploying"
          sleep 10
      - run: |
          echo "Step 4 deploying"
          sleep 10
      - run: |
          echo "Step 5 deploying"
          sleep 10
