name: test
on:
  push:
    branches: [main]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run docker action 
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: 'Cyniade'

      - name: Output time data
        run: echo "time is ${{ steps.hello-action.outputs.time }} when triggered"

